const SQLQuery = {
  MASTER_ITEM: `INSERT INTO master_item(
        mi_name,
        mi_category,
        mi_status,
        mi_createdby,
        mi_createddate) VALUES ?`,
  MASTER_CATEGORY: `INSERT INTO master_category(
        mc_name,
        mc_status,
        mc_createdby,
        mc_createddate) VALUES ?`,
  EMPLOYEE: `INSERT INTO employee(
            e_fullname,
            e_position,
            e_department,
            e_username,
            e_password,
            e_access,
            e_status,
            e_createdby,
            e_createddate) VALUES ?`,
  PRODUCT: `INSERT INTO product(
                p_assetcontrol,
                p_serial,
                p_itemname,
                p_category,
                p_podate,
                p_ponumber,
                p_warrantydate,
                p_status) VALUES ?`,
  DEPLOY: `INSERT INTO deploy(
                    d_assetcontrol,
                    d_serial,
                    d_date,
                    d_deployby,
                    d_deployto,
                    d_referenceno) VALUES ?`,
  RETURNITEM: `INSERT INTO returnitem(
        r_assetcontrol,
        r_serial,
        r_date,
        r_returnby,
        r_returnfrom,
        r_referenceno) VALUES ?`,
  REPAIRITEM: `INSERT INTO repair(
            r_assetcontrol,
            r_serial,
            r_date,
            r_repairby,
            r_referenceno) VALUES ?`,
  SOLDITEM: `INSERT INTO sold(
                s_assetcontrol,
                s_serial,
                s_date,
                s_soldby,
                s_soldto,
                s_referenceno) VALUES ?`,
  TRANSFERITEM: `INSERT INTO transfer(
                    t_assetcontrol,
                    t_serial,
                    t_date,
                    t_transferby,
                    t_from,
                    t_receiveby,
                    t_to,
                    t_referenceno) VALUES ?`,
  MASTER_DEPARTMENT: `INSERT INTO master_department(
        md_name,
        md_status,
        md_createdby,
        md_createddate) VALUES ?`,
  MASTER_POSITION: `INSERT INTO master_position(
        mp_name,
        mp_status,
        mp_createdby,
        mp_createddate) VALUES ?`,
  MASTER_ACCESS: `INSERT INTO master_access(
            ma_name,
            ma_status,
            ma_createdby,
            ma_createddate) VALUES ?`,
  MASTER_CLIENT: `INSERT INTO master_client(
        mc_branch,
        mc_company,
        mc_status,
        mc_createdby,
        mc_createddate) VALUES ?`,
  MASTER_ITEM_PRICE: `INSERT INTO master_item_price(
            mip_itemid,
            mip_fobprice,
            mip_status,
            mip_createdby,
            mip_createddate) VALUES ?`,
  PRICE_HISTORY: `INSERT INTO price_history(
                ph_itempriceid,
                ph_fobprice,
                ph_status,
                ph_createdby,
                ph_createddate) VALUES ?`,
  DEFFECTIVEITEM: `INSERT INTO deffectiveitem(
        d_assetcontrol,
        d_itemserial,
        d_remarks,
        d_date,
        d_referenceno) VALUES ?`,
  REPLACEITEM: `INSERT INTO replaceitem(
            r_assetcontrol,
            r_itemserial,
            r_replacedserial,
            r_remarks,
            r_date,
            r_replacedby,
            r_referenceno) VALUES ?`,
};
